"use client";
import { ThreeDMarquee } from "@/components/ui/3d-marquee";

export function ThreeDMarqueeDemo() {
  const images = [
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Raju Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shahid",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Profoelctron Solutions",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Nuzrat Carpet Emporium",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Nuzrat Carpet Emporium",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Profonet Solutions",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Armaan Home",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Armaan Home",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "KarimXNuzrat",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "role 1",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Nuzrat Carpet Emporium",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Nuzrat Carpet Emporium",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Profonet Solutions",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Armaan Home",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "Armaan Home",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },
    {
      name: "Shah Alam",
      src: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Image 1",
      description:  "This product has truly transformed the way I work! The user experience is fantastic, and the support team is always there to help.",
      role: "KarimXNuzrat",
      rating: "⭐️⭐️⭐️⭐️⭐️",
    },

  ];


  
  return (
    <div
      className="mx-auto my-10 max-w-screen-2xl rounded-3xl bg-gray-950/5 p-2 ring-1 ring-neutral-700/10 dark:bg-neutral-800">
      <ThreeDMarquee images={images}/>
    </div>
  );
}
